function createFlorentineGraph(g1,subgraphNodes)
%CREATEFIGURE(g1)
%  G1:  graph or digraph object

%  Auto-generated by MATLAB on 27-Jun-2019 12:25:09

% Create figure
figure;
set(gca, 'visible', 'off');
% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
h = plot(g1,'MarkerSize',14,'Marker','hexagram','NodeFontName','SansSerif',...
    'NodeFontSize',14,...
    'LineWidth',2,...
    'EdgeColor',[0.53,0.57,0.49],...
    'EdgeLabel',{},...
    'NodeLabelMode','auto',...
    'Layout',...
    'force');

subg1 = subgraph(g1,subgraphNodes);
g1Copy = graph([],[],[],g1.Nodes.Name);
g1Copy = addedge(g1Copy,subg1.Edges);
g1Copy.Nodes
g1Copy.Edges
highlight(h,g1Copy,'NodeColor','r','EdgeColor','b','LineWidth',4,'MarkerSize',20,'NodeFontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1.98267458663308 2.11624796946377]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-3.04868610208811 2.50055466044907]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[],'YTick',[]);
